name = "category-theory-in-context-lean"
version = "0.1.0"
keywords = ["math"]
defaultTargets = ["CategoryTheoryInContextLean"]

[leanOptions]
pp.unicode.fun = true # pretty-prints `fun a ↦ b`
autoImplicit = false
relaxedAutoImplicit = false
weak.linter.mathlibStandardSet = true
maxSynthPendingDepth = 3

[[require]]
name = "mathlib"
scope = "leanprover-community"

[[lean_lib]]
name = "CategoryTheoryInContextLean"
